spring:
  application:
    name: Auth

  datasource:
    url: jdbc:mysql://localhost:3306/microservice_employee
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8083

jwt:
  secret: "ajfwqejlfqwlei10923409312ljlwefaljfsajkldfjwsljs134qwfcs"