spring:
  application:
    name: Employee

  datasource:
    url: jdbc:mysql://localhost:3306/microservice_employee
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
